---
version: '2.1'
services:

  zookeeper-2:
      restart: always
      image: "zookeeper:3.5"
      hostname: zookeeper-2
      container_name: zookeeper-2
      ports:
        - "2181:2181"
      environment:
        ZOO_MY_ID: 2
        ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
      volumes:
        - ./zoo2/zk-data:/var/lib/zookeeper/data
        - ./zoo2/zk-txn-logs:/var/lib/zookeeper/log
      network_mode: "host"

  kafka-2:
      image: confluentinc/cp-kafka:5.3.1
      hostname: kafka-2
      container_name: kafka-2
      depends_on:
        - zookeeper-2
      ports:
        - "9093:9093"
      environment:
        KAFKA_BROKER_ID: 2
        KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://IP_ADDRESS_SERVER_2:19093,LISTENER_DOCKER_EXTERNAL://IP_ADDRESS_SERVER_2:9093
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
        KAFKA_ZOOKEEPER_CONNECT: IP_ADDRESS_SERVER_1:2181,IP_ADDRESS_SERVER_2:2181,IP_ADDRESS_SERVER_3:2181
      volumes:
        - ./kafka2/kafka-data:/var/lib/kafka/data
      network_mode: "host"
      restart: always
  
  kafka-connect-2:
      image: confluentinc/cp-kafka-connect:5.3.1
      container_name: kafka-connect-2
      depends_on:
        - kafka-2
        - zookeeper-2
      ports:
        - "8083:8083"
      environment:
        CONNECT_BOOTSTRAP_SERVERS:IP_ADDRESS_SERVER_1:19092,IP_ADDRESS_SERVER_2:19093,IP_ADDRESS_SERVER_3:19094
        CONNECT_REST_ADVERTISED_HOST_NAME: IP_ADDRESS_SERVER_2
        CONNECT_REST_PORT: 8083
        CONNECT_GROUP_ID: kafka-connect-group
        CONNECT_CONFIG_STORAGE_TOPIC: kafka-connect-configs
        CONNECT_OFFSET_STORAGE_TOPIC: kafka-connect-offsets
        CONNECT_STATUS_STORAGE_TOPIC: kafka-connect-status
        CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
        CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
        CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
        CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
        CONNECT_ZOOKEEPER_CONNECT: IP_ADDRESS_SERVER_1:2181,IP_ADDRESS_SERVER_2:2181,IP_ADDRESS_SERVER_3:2181
        CONNECT_PLUGIN_PATH: /usr/share/java
      network_mode: "host"
      restart: always
