---
version: '2.1'
services:

  zookeeper-3:
      restart: always
      image: "zookeeper:3.5"
      hostname: zookeeper-3
      container_name: zookeeper-3
      ports:
        - "2181"
      environment:
        ZOO_MY_ID: 3
        ZOO_SERVERS: server.1=IP_ADDRESS_SERVER_1:2888:3888;2181 server.2=IP_ADDRESS_SERVER_2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
        ZOO_TICK_TIME: 2000
        ZOO_INIT_LIMIT: 10
        ZOO_SYNC_LIMIT: 5
        ZOO_MAX_CLIENT_CNXNS: 60
        ZOO_4LW_COMMANDS_WHITELIST: "conf,cons,dump,envi,ruok,stat,wchs,wchc,wchp,mntr"
        ZOO_LOG4J_PROP: "INFO,ROLLINGFILE"
      volumes:
        - ./zoo3/data:/data
        - ./zoo3/datalog:/datalog
        - ./zoo3/logs:/logs

  kafka-3:
      image: confluentinc/cp-kafka:5.3.1
      container_name: kafka-3
      depends_on:
        - zookeeper-3
      ports:
        - "9094:9094"
        - "19094:19094"
      environment:
        KAFKA_BROKER_ID: 3
        KAFKA_ADVERTISED_HOST_NAME: IP_ADDRESS_SERVER_3
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://IP_ADDRESS_SERVER_3:19094,LISTENER_DOCKER_EXTERNAL://IP_ADDRESS_SERVER_3:9094
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_ZOOKEEPER_CONNECT: IP_ADDRESS_SERVER_1:2181,IP_ADDRESS_SERVER_2:2181,IP_ADDRESS_SERVER_3:2181
      volumes:
        - ./kafka3/kafka-data:/var/lib/kafka/data
      restart: always

  schema-registry-3:
      image: confluentinc/cp-schema-registry:5.3.1
      container_name: schema-registry-3
      depends_on:
        - zookeeper-3
        - kafka-3
      ports:
        - "8081:8081"
      environment:
        SCHEMA_REGISTRY_HOST_NAME: schema-registry-3
        SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: IP_ADDRESS_SERVER_1:2181,IP_ADDRESS_SERVER_2:2181,IP_ADDRESS_SERVER_3:2181
        SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://IP_ADDRESS_SERVER_1:19092,PLAINTEXT://IP_ADDRESS_SERVER_2:19093,PLAINTEXT://IP_ADDRESS_SERVER_3:19094
      restart: always

  kafka-connect-3:
      image: confluentinc/cp-kafka-connect:5.3.1
      container_name: kafka-connect-3
      depends_on:
        - kafka-3
        - zookeeper-3
      ports:
        - "8083:8083"
      environment:
        CONNECT_BOOTSTRAP_SERVERS: IP_ADDRESS_SERVER_1:19092,IP_ADDRESS_SERVER_2:19093,IP_ADDRESS_SERVER_3:19094
        CONNECT_REST_ADVERTISED_HOST_NAME: IP_ADDRESS_SERVER_3
        CONNECT_REST_PORT: 8083
        CONNECT_GROUP_ID: kafka-connect-group
        CONNECT_CONFIG_STORAGE_TOPIC: kafka-connect-configs
        CONNECT_OFFSET_STORAGE_TOPIC: kafka-connect-offsets
        CONNECT_STATUS_STORAGE_TOPIC: kafka-connect-status
        CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
        CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
        CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
        CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
        CONNECT_ZOOKEEPER_CONNECT: IP_ADDRESS_SERVER_1:2181,IP_ADDRESS_SERVER_2:2181,IP_ADDRESS_SERVER_3:2181
        CONNECT_PLUGIN_PATH: /usr/share/java
      restart: always

  ksql-server-3:
      image: confluentinc/cp-ksql-server:5.3.1
      container_name: ksql-server-3
      depends_on:
        - kafka-3
        - kafka-connect-3
      ports:
        - "8088:8088"
      environment:
        KSQL_BOOTSTRAP_SERVERS: IP_ADDRESS_SERVER_1:19092,IP_ADDRESS_SERVER_2:19093,IP_ADDRESS_SERVER_3:19094
        KSQL_LISTENERS: http://0.0.0.0:8088/
        KSQL_KSQL_SERVICE_ID: ksql_service_1_
        KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://IP_ADDRESS_SERVER_1:8081"
      restart: always
